### ISSUE TITLE
work for cs 1.6?

### ISSUE THREAD

**Issue by ksm200** [XaviFortes/IPTables-DDOS-Protection#1]
its work for cs 1.6 udp port ?

**Comment by XaviFortes** [comment]
You can try and tell me if this worked for you. However you can later remove the tables with this commands 
`sudo iptables -Z; sudo iptables -F; sudo iptables -P INPUT ACCEPT; sudo iptables -P FORWARD ACCEPT; sudo iptables -P OUTPUT ACCEPT
`
